version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    pre_build:
      # Generate on-the-fly Sphinx configuration from Jupyter Book's _config.yml
      - "jupyter-book config sphinx docs/"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

formats:
  - pdf
  - epub
